title: Don Assamongkol Blog
description: Thoughts and opinions are my own.
url: "https://donassamongkol.com"

theme: minima
minima:
  skin: dark

header_pages:
  - quotes.md
  - contact.md

github:
  username: Don-Assamongkol1

show_excerpts: true

kramdown:
  input: GFM
